### ISSUE TITLE
Why not make this a pull request to shoulda matchers

### ISSUE THREAD

**Issue by alexandru-calinoiu** [fny/rspec-inherit_from_matcher#1]
Great gem, I was actually looking for a inheritance matcher, but it seems so weird to add a gem to my gem file just for this, why not make it a PR to https://github.com/thoughtbot/shoulda-matchers ?

**Comment by fny** [comment]
I'm not sure if this is in scope for `Shoulda::Matchers`, which is intended to be Rails specific (i.e. the tagline is "Simple One-Liner Tests for Rails".)

If anything, this could become part of `rspec/rspec-expectations`, but I'm not sure if RSpec would like to encourage the use of such a matcher. In theory, using `shared_examples_for` is a safer and more robust test strategy. @myronmarston: your two cents would be much appreciated.

**Comment by myronmarston** [comment]
> If anything, this could become part of rspec/rspec-expectations, but I'm not sure if RSpec would like to encourage the use of such a matcher. In theory, using shared_examples_for is a safer and more robust test strategy. @myronmarston: your two cents would be much appreciated.

This has come up before -- see rspec/rspec-expectations#709.  I still feel the same -- I don't think this belongs in rspec-expectations because I don't think it's a general purpose matcher.  You can read the discussion there for more info.
