### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by ClayShentrup** [fny/rspec-inherit_from_matcher#2]
1) `expect(String < BasicObject).to be(true)`

2) Inheritance doesn't really prove anything since your class can redefine all parent methods. Instead you want to use shared_behaviors.

3) [Don't use inheritance](http://wiki.c2.com/?CompositionInsteadOfInheritance).

**Comment by fny** [comment]
1 You get much, much better error messages.
2. Sometimes you actually need to make sure an ancestor/child exists.
3. Like all tools, inheritance has a time and place. For example, ***if*** you have a correctly modeled hierarchy, you gain the benefit of propagating changes from the base class to all subclasses, and it won't bite you later. I personally follow Sandi Metz's advice, and use at most one level of inheritance at the "leaves" of the data model.
4. You don't have to use this gem!

**Comment by ClayShentrup** [comment]
I think anyone who reads Sandi Metz is going to live in a pretty sane hygienic world.

> if you have a correctly modeled hierarchy, you gain the benefit of propagating changes from the base class to all subclasses

Hm, I don't see how composition fails to solve this.

In my last Rails project, I zealously avoided any use of </include/extend, except where forced to by third party code, and it worked out really nicely.

One thing I like about these kinds of rules, practically speaking, is that it's much easier to enforce a rule that says "no inheritance" than to keep a diverse team disciplined about fuzzy rules about when it's worth the complexity. I guess I'm also biased because I've never seen a case where I thought inheritance was a good idea.

Thanks for the feedback.
